### ISSUE TITLE
 Android Tracking Issue

### ISSUE THREAD

**Issue by Dispersia** [hecrj/iced#891]
As a follow up to https://github.com/hecrj/iced/issues/302, but for android specifically, this is a tracking issue to address the issues highlighted in my inital post. Now that https://github.com/hecrj/iced/pull/830 is merged can start working on these individually.
 
 Required to run on android:
- [ ] Move off of Bgra8UnormSrgb, should be requesting swapchains preferred format
- [ ] Handle Suspend/Resumed events from winit
- [ ] Redraw Requested is not implemented on android, temporarily just needs to draw on the spot until https://github.com/rust-windowing/winit/pull/1822 is completed.

 Better Experience:
- [ ] Font loading doesn't working, as font-kit relies on things that don't exist on android
- [ ] Sizing is quite a bit messed up, not sure if iced currently handles different dpi's, but need to look into that and implement that here.

 Will update with prs as I work through it.

**Comment by ColonelThirtyTwo** [comment]
Looks like winit has the redraw request stuff, via https://github.com/rust-windowing/winit/pull/1953

**Comment by hecrj** [comment]
As I mentioned in https://github.com/iced-rs/iced/pull/631#issuecomment-897369162, this is out of scope for now!
